import libs = nanoflann%lib{nanoflann}

for t: cxx{* -matrix_example}
{
  n = $name($t)
  ./: exe{$n}: $t hxx{*} $libs testscript
}

import libs += Eigen%lib{Eigen}
./: exe{matrix_example}: hxx{*} cxx{matrix_example} $libs testscript
