import libs = nanoflann%lib{nanoflann}

for src: cxx{* -matrix_example}
{
  t = $name($src)
  ./: exe{$t}: $src hxx{*} $libs testscript
}

import libs += Eigen%lib{Eigen}
./: exe{matrix_example}: hxx{*} cxx{matrix_example} $libs testscript
