import nanoflann = nanoflann%lib{nanoflann}

for t: cxx{* -matrix_example}
{
  n = $name($t)
  ./: exe{$n}: $t hxx{*} $nanoflann
}

import Eigen = Eigen%lib{Eigen}
./: exe{matrix_example}: hxx{*} cxx{matrix_example} $nanoflann $Eigen
