lib{nanoflann}: hxx{nanoflann}
{
  cxx.export.poptions = "-I$src_base"
}

if ($cxx.target.system != 'win32-msvc')
{
  cxx.libs += -pthread
  lib{nanoflann}: cxx.export.libs += -pthread
}

hxx{*}: install = include/
